### ISSUE TITLE
Using a controller to open crafting table will crash the game

### ISSUE THREAD

**Issue by FanghanHu** [zheka2304/InnerCore#2]
First of all, I'm surprised that nobody have posted a single issue here.

Since I can't find a way to copy and paste the exception stacktrace, I am just going to post the first few lines:
```
Non-Fatal error occurred in callback ItemUse

StackTrace:
at screen_workbench_a2fa22_74a155:187(anonymous)

org.mozilla.javascript.WrappedException: Wrapped android.view.ViewRootImpl@CalledFromWrongThreadException:Only the original thread that created a view hierarchy can touch its views. (screen_workbench_a2fa22_74a155:187#187)
...
....... (not very interesting stuff)
...
zhekasmirnov.launcher.api.runtime.Callback.invokeAPICallbackUnsafe(Callback.java:46)
zhekasmirnov.launcher.api.NativeCallback.onItemUsed(NativeCallback.java:326)
```

yup, I just typed it all by hand, hope it helps you fixing the problem.

btw, you really need to get this issue tracker out in your website, 
including a copy of mcpe is probably VERY VERY bad for your software, I like your work a lot, and I hope you figure out a way for people to get their copy of mcpe legally, good work, and best of luck to you.

**Comment by FanghanHu** [comment]
Using Inner Core 1.1.2.42 and a bluetooth controller.
while using the controller, mcpe uses another set of UI, that could be the cause.

**Comment by DY4R** [comment]
Hello, I'm using inner core latest version
Everytime when I try to open or generate a world in innercore it imdediatly crashes

When I first time open the Innercore it gives 

Non fatal error 

and some lines down it says

[WARNING] Failed to load crash handler 

Is there any solutions? Help me please.
