### ISSUE TITLE
Compile Mods in Java instead of Javascript? 

### ISSUE THREAD

**Issue by 1reverseengineer** [zheka2304/InnerCore#7]
Привет.

**1.** Is it possible to write and compile MCPE Inner Core mods in Java instead of Javascript? (_yes I know they're not the same language/interchangeable_)
Javascript is sadly the scorch of earth and I don't want to go to a psychiatric clinic, writing a single line of JS ever again. 

**2.** What is Horizon Modding Kernel compared to Inner Core?

Thank you for creating Inner Core,

**Comment by 1reverseengineer** [comment]
Still alive?

**Comment by zheka2304** [comment]
Horizon is continuation of Inner Core with alot of new possibilities, multiplayer and newer version of the game.

It supports modding in java, but at the current moment java-oriented API is in deep development and in many cases it requires to use js-oriented API in java. The full java API will be ready in 1-2 month I guess.

To develop in java you should use innercore mod toolchain (I have its repo on this account, but it is supported not by me). 

I suggest you to wait about 2 month. After this period of time java development will be in much better state.

**Comment by 1reverseengineer** [comment]
Thank you for creating Inner Core and thank you for answering. I will wait and support you with bug reports when the Java Version drops.
